# Generated by Django 3.1 on 2020-09-07 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20200907_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(blank=True, default='Anonymous', max_length=30),
        ),
    ]
