# Generated by Django 3.1 on 2020-09-07 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20200907_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(blank=True, default='K', max_length=30),
        ),
    ]
